- hosts: all
  roles:
    - role: palmerc.ansible_role_xcode
      xcode_version: 10.1
      xcode_src: Xcode_10.1.xip
    - role: lhazlewood.xcode_clt
    - role: geerlingguy.homebrew
      homebrew_installed_packages:
        - git
        - autoconf
        - automake
        - libtool
        - wget
        - pkg-config
        - libxslt
        - hdf5
        - libsoup
        - pygobject3
        - bash
        - swig
        - numpy
        - gcc
        - llvm
        - librsvg
        - tschoonj/tap/gtkmm-plplot
        - libpeas
        - json-glib

